<?php


function stats_mail($key, &$message, $params) {
 	switch ($key) {
	   	case 'cusmail':
		   	$message['headers'] = array(
		      'content-type' => 'text/html',
		      'MIME-Version' => '1.0',
		    );

			$message['from'] = 'anmolchaudhary96@gmail.com';//\Drupal::config('system.site')->get('mail');
			$message['subject'] = t('Test');
			$message['body'][] = $params['message'];
			break;
 	}
}


function get_details(){
	
	if(\Drupal::database()->schema()->tableExists('application_details')){
		$data = [];
		$query = \Drupal::database()->select('application_details', 'ad');
		$query->fields('ad', ['id']);
		$query->fields('ad', ['username']);
		$query->fields('ad', ['email']);
		$query->fields('ad', ['mobile']);
		$query->fields('ad', ['gender']);
		$query->fields('ad', ['question']);
		$query->orderBy('ad.changed', 'ASC');
//		$query->condition('ad.id', $id);
		$rows = $query->execute();
		$result = $rows->fetchAll();
		
		return $result;
	}

}

// function updateDetails($id){
// 	if(\Drupal::database()->schema()->tableExists('application_details')){
//     $result = get_by_query($id);
//     kint($result);
//     $query = \Drupal::database()->update('application_details');
//     $query->fields(['username' =>$result[0]->username ,'email' => $result[0]->email ,'mobile' => $result[0]->mobile,
//     'gender' => $result[0]->gender,'question' => $result[0]->question,]);
//     $query->condition('id',$id);
//     $result = $query->execute();
//     //$result = $result->fetchAll();

    
// 	}

//}

function get_by_query($id) {

	global $base_url;
	if(\Drupal::database()->schema()->tableExists('application_details'))
	$query = \Drupal::database()->select('application_details', 'ad');
	$query->fields('ad', ['id']);
	$query->fields('ad', ['username']);
	$query->fields('ad', ['email']);
	$query->fields('ad', ['mobile']);
	$query->fields('ad', ['gender']);
	$query->fields('ad', ['question']);
	$query->orderBy('ad.changed', 'ASC');
	$query->condition('ad.id', $id);
	$rows = $query->execute();
	
	$result = $rows->fetchAll();

	return $result;
}


?>